version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysqlICPC
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd1
      MYSQL_DATABASE: neighbor
      MYSQL_USER: msg
      MYSQL_PASSWORD: p@ssw0rd2
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: mysql:8.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_PWD: p@ssw0rd1
    command: >
      bash -c '
        mysql -h mysqlICPC -uroot -e "
          ALTER USER '\''root'\''@'\''%'\'' IDENTIFIED WITH mysql_native_password BY '\''p@ssw0rd1'\'';
          FLUSH PRIVILEGES;
        ";
      '
    restart: "no"

volumes:
  mysql_data:
